### PR TITLE
Query uses both limit and joint prefetch OD-17015

### PR DESCRIPTION
**Pull request by KeyrisXdSnow**

### CODE REVIEW

**Review by ari — CHANGES_REQUESTED** [review]
@KeyrisXdSnow How is your change fixing the problem? You've left the query in place with limit and joint prefetch.

**Comment by KeyrisXdSnow** [comment]
> @KeyrisXdSnow How is your change fixing the problem? You've left the query in place with limit and joint prefetch.

I save this logic cause is behavior witch we are expect.
However, the problem lies in the fact that we cannot use `.limit()` and `.prefetch()` methods together in a cayenne query.

In my case, `.prefetch()` used in cayenne query.
SelectQuery is execute.
And I limit selected items by groovy.

**Comment by ari** [comment]
But we still have prefetch and limit in the query. So you fixed nothing.

**Comment by KeyrisXdSnow** [comment]
> 

Understand, fixed

**Comment by ari** [comment]
Would a disjoint prefetch make more sense? What's the purpose of the limit here? Look at the commit history to try and understand why this was added.

**Comment by ari** [comment]
What is a 'registry enhancement'? Is this the query which finds session conflicts?

For only three records, I think the prefetch is just not giving us any substantial performance improvement. Let's keep the limit and remove the prefetch.

**Comment by KeyrisXdSnow** [comment]
> What is a 'registry enhancement'? Is this the query which finds session conflicts?
> 
> For only three records, I think the prefetch is just not giving us any substantial performance improvement. Let's keep the limit and remove the prefetch.

'Registry enhancement' this is a name of epic in which this logic was added.
From my point of view, you are indeed right. This optimization does not really improve performance.

But I am afraid of since I haven't work and  encountered this task in any cases, this can potentially lead to problems that I simply do not see now.

**Pull request closed without merging**
