### PR TITLE
OD-16231_lead_API

### PR DESCRIPTION
**Pull request by yuryyas**

### CODE REVIEW

**Comment by ari** [comment]
@GFilipovich Did we add automation events here?

**Comment by ArtyomKravchenko** [comment]
@ari  what do you mean-'automation events'. What the events do you expect?

**Comment by ari** [comment]
Can you add create/edit/delete/etc events to automation for the new entities?

**Comment by ArtyomKravchenko** [comment]
Yes, it works from the box

**Review by GFilipovich — APPROVED** [review]
Verified in branch

**Comment by ArtyomKravchenko** [comment]
@GFilipovich 
I have merged it locally (since github blocked merge because of conflict ) and pushed to remote main. retest main please

**Pull request merged**
