### PR TITLE
Clustered onCourse servers

### PR DESCRIPTION
**Pull request by stariy95**
This PR is a part of ishgroup/onCourse-roadmap#12

Number generation is done via a sequence like stored procedure on the MySQL side. In-memory queue is used to perform some buffering on the server side.

I'm not sure about proper liquibase changeset naming, so I just used a placeholder, that should be fixed.

### CODE REVIEW

**Comment by ari** [comment]
How portable is this? Will it run on:

* mysql
* mariadb
* RDS Aurora

**Comment by stariy95** [comment]
I've tested this on MariaDB and MySQL. 
As for AWS Aurora, it supports stored procedures and no limitations mentioned in the docs, so it should be good too.

**Comment by ArtyomKravchenko** [comment]
Hey Nikita
I am not quite sure why do we need stored procedure here. To lock SequenceSupport row while updating next id column?
Could we do it with regular TransactionalOperation in cayenne?

**Comment by stariy95** [comment]
Yes, `TransactionalOperation` should work too. The procedure seems a little bit more versatile for me. It could be used outside of Cayenne, keeping everything in order, and the implementation could be changed without code modifications. E.g., we could change it to use separate tables for each sequence if there would be great lock contention.
Thought, not sure if these are important factors for your case.

**Comment by ari** [comment]
My main problem with procedures is that we are tied to particular flavours of SQL. Some future Aurora, postgresql or other system we want to support may have small differences we need to understand and test.

I like the idea that the database is just a stupid data store.

**Comment by stariy95** [comment]
Pushed a new implementation that doesn't use stored procedure. It uses Cayenne transaction and `SELECT .. FOR UPDATE` locking instead.

**Comment by ari** [comment]
xx.upgrade.yml looks like a strange filename

**Comment by ArtyomKravchenko** [comment]
@ari  leave it for me please(I mean xx.upgrade.yml). I will rename it (use correct version name) when I will merge Nikita's PR

**Comment by ArtyomKravchenko** [comment]
I see that we could do it right away, PR looks fine. Nikita, please use 58 version number

**Pull request merged**
